# Generated by Django 2.2.5 on 2019-12-02 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_page',
            name='picture',
            field=models.ImageField(default='media/redCross.jpg', upload_to='', width_field=100),
        ),
        migrations.AddField(
            model_name='agencies_page',
            name='requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_In_Progress'),
        ),
        migrations.AddField(
            model_name='cause',
            name='news_articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.News_Articles'),
        ),
        migrations.AddField(
            model_name='news_articles',
            name='picture',
            field=models.ImageField(default='media/redCross.jpg', upload_to='', width_field=100),
        ),
        migrations.AddField(
            model_name='request_fulfilled',
            name='request_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_In_Progress'),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='requests_fulfilled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('picture', models.ImageField(default='media/defaultProfilePic.jpg', upload_to='', width_field=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agencies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Profile'),
        ),
    ]
