# Generated by Django 2.2.8 on 2019-12-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_articles',
            name='picture',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
