# Generated by Django 2.2.5 on 2019-11-18 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_page',
            name='picture',
            field=models.ImageField(default='media/redCross.jpg', upload_to='', width_field=100),
        ),
        migrations.AddField(
            model_name='agencies',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agencies_page',
            name='requests',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_In_Progress'),
        ),
        migrations.AddField(
            model_name='cause',
            name='news_articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.News_Articles'),
        ),
        migrations.AddField(
            model_name='news_articles',
            name='picture',
            field=models.ImageField(default='media/redCross.jpg', upload_to='', width_field=100),
        ),
        migrations.AddField(
            model_name='request_in_progress',
            name='request_fulfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='requests_fulfilled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
        ),
    ]
