# Generated by Django 2.2.5 on 2019-11-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_page',
            name='picture',
            field=models.ImageField(default=1, upload_to='', width_field=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agencies_page',
            name='requests',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_In_Progress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cause',
            name='news_articles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.News_Articles'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news_articles',
            name='picture',
            field=models.ImageField(default=1, upload_to='', width_field=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request_in_progress',
            name='request_fulfillment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account_page',
            name='requests_fulfilled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
        ),
    ]
