# Generated by Django 2.2.5 on 2019-11-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191118_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_articles',
            name='picture',
            field=models.URLField(max_length=500),
        ),
    ]
