# Generated by Django 2.2.5 on 2019-11-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191113_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_articles',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
