# Generated by Django 2.2.5 on 2019-11-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_news_articles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_articles',
            name='picture',
            field=models.ImageField(upload_to='uploads/', width_field=100),
        ),
    ]
