# Generated by Django 2.2.5 on 2019-11-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20191118_2321'),
        ('myapp', '0004_auto_20191113_2322'),
    ]

    operations = [
    ]
