# Generated by Django 2.2.5 on 2019-11-18 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20191118_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencies',
            name='user',
        ),
        migrations.AlterField(
            model_name='account_page',
            name='picture',
            field=models.ImageField(upload_to='', width_field=100),
        ),
        migrations.AlterField(
            model_name='account_page',
            name='requests_fulfilled',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencies_page',
            name='requests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_In_Progress'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='news_articles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.News_Articles'),
        ),
        migrations.AlterField(
            model_name='news_articles',
            name='picture',
            field=models.ImageField(upload_to='uploads/', width_field=100),
        ),
        migrations.AlterField(
            model_name='request_in_progress',
            name='request_fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
        ),
    ]
