# Generated by Django 2.2.5 on 2019-12-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191118_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_articles',
            name='picture',
            field=models.URLField(max_length=100),
        ),
    ]
