# Generated by Django 2.2.8 on 2019-12-11 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_in_progress',
            name='item',
            field=models.CharField(default=datetime.datetime(2019, 12, 11, 18, 3, 40, 998591), max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request_in_progress',
            name='amount_fulfilled',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='request_in_progress',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
