# Generated by Django 2.2.8 on 2019-12-12 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191211_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_in_progress',
            name='request_fulfillment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_Fulfilled'),
        ),
    ]
