# Generated by Django 2.2.8 on 2019-12-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20191212_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_in_progress',
            name='request_fulfillment',
        ),
    ]
