# Generated by Django 2.2.8 on 2019-12-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191205_2127'),
        ('myapp', '0011_remove_request_in_progress_request_fulfillment'),
    ]

    operations = [
    ]
