# Generated by Django 2.2.8 on 2019-12-15 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0012_merge_20191215_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('picture', models.ImageField(blank=True, default='defaultProfilePic.jpg', null=True, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='account_page',
            name='requests_fulfilled',
        ),
        migrations.RemoveField(
            model_name='agencies_page',
            name='requests',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.RenameField(
            model_name='request_fulfilled',
            old_name='fulFilledAmount',
            new_name='fulfilled_amount',
        ),
        migrations.RenameField(
            model_name='request_fulfilled',
            old_name='promisedAmount',
            new_name='promised_amount',
        ),
        migrations.RenameField(
            model_name='request_fulfilled',
            old_name='promisedArrival',
            new_name='promised_arrival',
        ),
        migrations.RemoveField(
            model_name='cause',
            name='news_articles',
        ),
        migrations.AddField(
            model_name='agencies',
            name='causes',
            field=models.ManyToManyField(blank=True, to='myapp.Cause'),
        ),
        migrations.AddField(
            model_name='agencies',
            name='picture',
            field=models.ImageField(blank=True, default='defaultProfilePic.jpg', null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='agencies',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cause',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request_fulfilled',
            name='request_in_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Request_In_Progress'),
        ),
        migrations.AddField(
            model_name='request_fulfilled',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_in_progress',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Agencies'),
        ),
        migrations.AlterField(
            model_name='agencies',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='news_articles',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news_articles',
            name='picture',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news_articles',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='request_in_progress',
            name='date_requested',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Account_Page',
        ),
        migrations.DeleteModel(
            name='Agencies_Page',
        ),
        migrations.AddField(
            model_name='profile',
            name='agencies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.Agencies'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
