# Generated by Django 2.2.8 on 2019-12-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20191215_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_in_progress',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
